source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails' ,'~> 5.1'  # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'